### PR TITLE
check_registry code

### PR DESCRIPTION
**Pull request by edeediong**

### CODE REVIEW

**Comment by jspaaks** [comment]
Hi @edeediong, can you merge the master into your branch --the diff is a bit big like this. Thanks!

**Comment by edeediong** [comment]
Oh i will... My code isn't working yet. Once it works fix it

**Comment by jspaaks** [comment]
OK, could you then mark this Pull Request as a draft by using the small button at the top right of this page? Thanks

**Comment by jspaaks** [comment]
@edeediong be advised the ``howfairis`` python package has moved to a new repo, see https://github.com/fair-software/badge/issues/31

**Pull request closed without merging**
